resource_group_name = "rg-ynov"
location            = "westeurope"
acr_name            = "acrynovdemo"
mysql_name          = "mysqlynov"
mysql_admin         = "adminwp"
mysql_password      = "WpSecure123@"
webapp_name         = "wpwebapp-ynov"
